# -*- coding: utf-8 -*-
"""utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wUvu50KNBgM2rE8K_6l30ZUqGcrWTfDj
"""

import torch
import torch.nn as nn

def gradient_penalty(critic,real,fake,device):
  BATCH_SIZE, C, H,W = real.shape
  epsilon = torch.rand((BATCH_SIZE,1,1,1)).repeat(1,C,H,W).to(decive)
  interpolated_image = real* epsilon + fake *(1-epsilon)

  mixed_score = critic(interpolated_image)

  gradient = torch.autograd.grad(
      inputs = interpolated_image,
      outputs = mixed_score,
      grad_outputs = torch.ones_like(mixed_score),
      create_graph = True,
      retain_graph = True,
  )[0]

  gradient = gradient.view(gradient.shape[0],-1)
  gradient_norm = gradient.norm(2,dim=1)
  gradient_penelty = torch.mean((gradient_norm - 1)**2)

  return gradient_penelty